logger:
  level: INFO
image_service:
  max_image_size_mb: 5
  allowed_extensions:
    - jpg
    - jpeg
    - png
    - gif
server:
  port: 8080
database:
  host: localhost
  port: 3307
  user: root
  password: root_password
  database: images_db
aws:
  host: http://localhost.localstack.cloud:4566
  region: "us-east-1"
  aws_access_key_id: key_id
  aws_secret_access_key: access_key
jwt:
  secret: secret-123
  alg: HS256
