server:
  port: 8080
database:
  host: localhost
  port: 3307
  user: root
  password: root_password
  database: images_db
aws:
  host: http://localhost.localstack.cloud:4566
  aws_access_key_id: key_id
  aws_secret_access_key: access_key
